spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://120.79.41.87:3306/gmdb
    username: root
    password: Keyanxiaofendui007
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
management:
  security:
    enabled: false

mybatis:
    configuration:
      map-underscore-to-camel-case: true



